-- Time to complete: 07:46 minutes

-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 14:23:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelo_conceitual_teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelo_conceitual_teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo_conceitual_teste` DEFAULT CHARACTER SET utf8 ;
USE `modelo_conceitual_teste` ;

-- -----------------------------------------------------
-- Table `modelo_conceitual_teste`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_conceitual_teste`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `foto_produto` VARCHAR(1000) NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  `nome_produto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_conceitual_teste`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_conceitual_teste`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_conceitual_teste`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_conceitual_teste`.`Pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `valor_total_pedido` DECIMAL(10,2) NOT NULL,
  `data_pedido` DATE NOT NULL,
  `forma_pagamento` VARCHAR(50) NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedido_Usuario_idx` (`Usuario_id_usuario` ASC),
  CONSTRAINT `fk_Pedido_Usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `modelo_conceitual_teste`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_conceitual_teste`.`Contem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_conceitual_teste`.`Contem` (
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade_contem` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_produto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`id_produto` ASC),
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`id_pedido` ASC),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `modelo_conceitual_teste`.`Pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `modelo_conceitual_teste`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
